name: lens
description: "Personalized News App - Get the latest headlines anytime, anywhere."
# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: "none" # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ^3.9.2

dependencies:
  bloc: ^9.0.1
  cached_network_image: ^3.4.1
  cloud_firestore: ^6.1.0
  cupertino_icons: ^1.0.8
  device_preview: ^1.3.1
  dio: ^5.9.0
  equatable: ^2.0.7
  firebase_auth: ^6.1.2
  firebase_core: ^4.2.1
  flutter:
    sdk: flutter
  flutter_bloc: ^9.1.1
  flutter_dotenv: ^6.0.0
  flutter_native_splash: ^2.4.7
  flutter_screenutil: ^5.9.3
  flutter_svg: ^2.2.3
  freezed_annotation: ^3.1.0
  go_router: ^17.0.1
  google_sign_in: ^6.3.0 
  json_annotation: ^4.9.0
  shared_preferences: ^2.5.3
  shorebird_code_push: ^2.0.5
  skeletonizer: ^2.1.0+1

dev_dependencies:
  build_runner: ^2.10.4
  flutter_launcher_icons: ^0.14.4
  flutter_lints: ^6.0.0
  flutter_test:
    sdk: flutter
  freezed: ^3.2.3
  json_serializable: ^6.11.2

flutter:
  uses-material-design: true
  assets:
    - shorebird.yaml
    - .env
    - assets/images/
    - assets/fonts/

  fonts:
    - family: Cairo
      fonts:
        - asset: assets/fonts/arabic/Cairo-Black.ttf
          weight: 900
        - asset: assets/fonts/arabic/Cairo-ExtraLight.ttf
          weight: 200
        - asset: assets/fonts/arabic/Cairo-Light.ttf
          weight: 300
        - asset: assets/fonts/arabic/Cairo-Medium.ttf
          weight: 500
        - asset: assets/fonts/arabic/Cairo-SemiBold.ttf
          weight: 600
    - family: Inter
      fonts:
        - asset: assets/fonts/english/Inter_24pt-Black.ttf
          weight: 900
        - asset: assets/fonts/english/Inter_28pt-Bold.ttf
          weight: 700
        - asset: assets/fonts/english/Inter_28pt-ExtraBold.ttf
          weight: 800
        - asset: assets/fonts/english/Inter_28pt-Light.ttf
          weight: 300
        - asset: assets/fonts/english/Inter_28pt-Medium.ttf
          weight: 500
        - asset: assets/fonts/english/Inter_28pt-Regular.ttf
          weight: 400

flutter_native_splash:
  color: "#F5F5F7"
  image: assets/images/iconsplash.jpg
  android: true
  ios: true


flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/images/app_icon.jpg"
  min_sdk_android: 21